# Generated by Django 3.1.3 on 2020-12-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='ABminus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ABplus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Aminus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Aplus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Bminus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Bplus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Ominus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Oplus',
            field=models.CharField(max_length=10),
        ),
    ]
