# Generated by Django 3.1.3 on 2020-12-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20201230_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='postingdate',
            field=models.CharField(max_length=100),
        ),
    ]
