# Generated by Django 3.1.3 on 2021-01-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20210101_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='AssocHB',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='ReferenceID',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
