# Generated by Django 3.1.3 on 2021-01-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0003_auto_20210101_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='AssocHB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='ReferenceID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
