# Generated by Django 3.1.3 on 2021-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0005_auto_20210101_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
