# Generated by Django 3.1.3 on 2021-01-01 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0008_auto_20210101_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
