# Generated by Django 3.1.3 on 2021-01-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0009_auto_20210101_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='expiry_date',
            field=models.CharField(max_length=100),
        ),
    ]
